sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: GIS4WvOkouqtQjtQUoOwCe3YN12abZLs9TzPPLD+k6ejOoYjmNmTu1S7kscJcr63lar1SUuO/LopoiazkbCbHjXRV6IXgUjZ49txeT9eVpWHjWr+Hpjxsjd54vg25QMbJ6Y9I6vRlpc+yrjDjPj4XVeIFfmgzX7ACwwFdLNgOBsuNDux4D7bevGMsFUMeTPRE7fokkPKBdvLnwb+JyFyMl7OiQBPEoM+gH+2Wh8mD+VEnzZ7lowfgS9BuCRBvHZU7bo+OqirkDZ+L8HDuVMW8fO5VmXiEoCR7mr6MGG6FQW1jVz+wdTFeKxpczbwjsemFAhTjvu3z6M+SNO+u5z59Pg0ejwx9aEw5aVYdv13h6hsdc9+sY7MjT8BPGrGH2O9aUltciQTFgGfOtFGWPHcGdrlnPqdndO5V2nOgJYeiqFS7MDllaIcJncP1754mV4yl3GBWZgv1+ZZK7EbWqyy8hLYpe21ajAV2JlUAL7hLrwwCYb36U7nOw9hiehE09k+672Mtw+/3/xfvtLQxOzLYdfL6N0sD5qvPR/M42u8EEY2CQcwxUjz6fXSXFVvQfSlKoVEBaSD+4hc63IqHfyTNdcorV7Qp1UpgWd1aWWiv2ycbgMfKtIlQooL05JOoyYq5CiqkC2YpF+++LCMJyZnObDWF7+jNFAxRjOOb1RE4wU=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: hwxc1nXnqJyIDkZRYVkKwhI33eQnCemYJ10wI4GQACyTwmbt/YRI5FJio9+BUzS3G+lWEMHlrE/hJsvPaonTiPwzGYABL9e1fPb12v/jZJj/r6gpKelbbRNFCTvUC4QTjxZ4qHrmnh1Qp23YmCnIB3GjkqtrX2IVv3zwACvP4W770e7bc6HDLSYIaRb9qC4OkWlBX8kSyddFfjXAl3yVQK3gBce5O5QHx5EqtU/rr/0hpY1/WRckgrUlNq+xprWVnwX348ho3jueMUoBQNU9KlHevlRKwaBnVMo4JEIGPzazMmqB6WYeD0uQcFfrFrNapwex5XWGAQGwDBwq+Sm2HphpHxnalFTHPIzHcXu0n29tVxnB1TjgG3COR5c41XhXJE59AGvoC0ukUL+ZytDoXQ+aFskAGXPst6D39/UEkaiEC/L2bKcKCzIXd9CliWTl4MxVERntKwq/FrlFslsx3cQC+fpopjKsU66fQicdnjlLddhfhrHlOp8vJ4OJhE5EsYpQr9sSPswC81V8b9RUREH8SybCOVmYUqvgiJb+N083HVx1xlXAeV2Bt8mGvo0ievxJUc1AFQ1XT2LdLwRhA+uF8aKljxzKt9OwfMz0vm4ZlEycrqy10NJ1lvWZa+FIcni3RXMfAeEGv/iN312sUc3dtaYu3w77SVhTVmTgqpc=
